// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import DeleteNotificationsListController from "./delete_notifications_list_controller"
application.register("delete-notifications-list", DeleteNotificationsListController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FooterNavController from "./footer_nav_controller"
application.register("footer-nav", FooterNavController)

import GruppettoFormHideController from "./gruppetto_form_hide_controller"
application.register("gruppetto-form-hide", GruppettoFormHideController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)

import SearchFilterController from "./search_filter_controller"
application.register("search-filter", SearchFilterController)

import TrackSubscriptionController from "./track_subscription_controller"
application.register("track-subscription", TrackSubscriptionController)
