// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GruppettoFormHideController from "./gruppetto_form_hide_controller"
application.register("gruppetto-form-hide", GruppettoFormHideController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)

import TrackSubscriptionController from "./track_subscription_controller"
application.register("track-subscription", TrackSubscriptionController)
